import ex0

print("Testing factory")
flameling = ex0.FlameFactory().create_base()
print(flameling.describe())
print(flameling.attack())
pyrodon = ex0.FlameFactory().create_evolved()
print(pyrodon.describe())
print(pyrodon.attack())
print("Testing factory")
aquabub = ex0.AquaFactory().create_base()
print(aquabub.describe())
print(aquabub.attack())
torragon = ex0.AquaFactory().create_evolved()
print(torragon.describe())
print(torragon.attack())
print("Testing battle")
print(flameling.describe())
print("vs.")
print(aquabub.describe())
print("fight!")
print(flameling.attack())
print(aquabub.attack())
