import ex1

print("Testing Creature with healing capability")
print("base:")
sproutling = ex1.HealingCreatureFactory().create_base()
print(sproutling.describe())
print(sproutling.attack())
print(sproutling.heal())
print("evolved:")
bloomelle = ex1.HealingCreatureFactory().create_evolved()
print(bloomelle.describe())
print(bloomelle.attack())
print(bloomelle.heal())
print("Testing Creature with transform capability")
print("base:")
shiftling = ex1.TransformCreatureFactory().create_base()
print(shiftling.describe())
print(shiftling.attack())
print(shiftling.transform())
print(shiftling.attack())
print(shiftling.revert())
print("evolved:")
Morphagon = ex1.TransformCreatureFactory().create_base()
print(Morphagon.describe())
print(Morphagon.attack())
print(Morphagon.transform())
print(Morphagon.attack())
print(Morphagon.revert())