import ex0
import ex1
import ex2

print("Tournament 0 (basic)")
print("[ (Flameling+Normal), (Healing+Defensive) ]")
print("*** Tournament ***")
print("2 opponents involved\n")
print("* Battle *")
flameling = ex0.FlameFactory().create_base()
pyrodon = ex0.FlameFactory().create_evolved()
aquabub = ex0.AquaFactory().create_base()
torragon = ex0.AquaFactory().create_evolved()
shiftling = ex1.TransformCreatureFactory().create_base()
Morphagon = ex1.TransformCreatureFactory().create_evolved()
sproutling = ex1.HealingCreatureFactory().create_base()
bloomelle = ex1.HealingCreatureFactory().create_evolved()
print(flameling.describe())
print("vs.")
print(sproutling.describe())
print("now fight!")
ex2.NormalStrategy().act(flameling)
ex2.DefensiveStrategy().act(sproutling)
print("\nTournament 1 (error)")
print("[ (Flameling+Aggressive), (Healing+Defensive) ]")
print("*** Tournament ***")
print("2 opponents involved")
print("\n* Battle *")
print(flameling.describe())
print("vs.")
print(sproutling.describe())
print("now fight!")
ex2.AggressiveStrategy().act(flameling)
print("\nTournament 2 (multiple)")
print("[ (Aquabub+Normal), (Healing+Defensive), (Transform+Aggressive) ]")
print("*** Tournament ***")
print("3 opponents involved")
print("\n* Battle *")
print(aquabub.describe())
print("vs.")
print(sproutling.describe())
print("now fight!")
ex2.NormalStrategy().act(aquabub)
ex2.DefensiveStrategy().act(sproutling)
print("\n* Battle *")
print(aquabub.describe())
print("vs.")
print(shiftling.describe())
print("now fight!")
ex2.NormalStrategy().act(aquabub)
ex2.AggressiveStrategy().act(shiftling)
print("\n* Battle *")
print(sproutling.describe())
print("vs.")
print(shiftling.describe())
print("now fight!")
ex2.DefensiveStrategy().act(sproutling)
ex2.AggressiveStrategy().act(shiftling)
